# -*- mode: python ; coding: utf-8 -*-
'''
        Copyright (c) 2025 Easy
Easy Transcriber is licensed under Mulan PSL v2.
You can use this software according to the terms and conditions of the Mulan PSL v2.
You may obtain a copy of Mulan PSL v2 at:
        http://license.coscl.org.cn/MulanPSL2
'''


a = Analysis(
    ['EasyTranscriber.py'],
    pathex=[],
    binaries=[],
    datas=[('OCR','OCR'),("pictures",'pictures'),('pictures\\icn.ico','.'),("C:\\Users\\Easy\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pyecharts",'pyecharts')],
    hiddenimports=['os',
    'sys',
    'cy',
    'doc_to_docx',
    'ffmpeeg',
    'jpg_to_pdf',
    'pdf',
    'png_to_jpg',
    'pxmm',
    'spzm1',
    'tpbl',
    'Ui_cutpi',
    'Ui_cutvdo',
    'Ui_fps',
    'Ui_frontbebind',
    'Ui_gif',
    'Ui_key',
    'Ui_markrotatetrainkle',
    'Ui_mode',
    'Ui_piform',
    'Ui_tiaoz',
    'Ui_viwtmk',
    'Ui_wd',
    'Ui_zim',
    'UI004',
    'pyecharts.options',
    'pyecharts.charts.WordCloud',
    'jieba',
    'ctypes',
    'win32com.client',
    'PIL.Image',
    'multiprocessing',
    'pymupdf',
    'cv2',
    'PIL.ImageFont',
    'PIL.ImageDraw',
    'numpy',
    'ast',
    'PyQt6.QtCore',
    'PyQt6.QtGui',
    'PyQt6.QtWidgets',
    'PyQt6',
    'time',
    'io',
    'qt_material',
    'atexit',
    'subprocess',
    'json.loads',
    'json.dumps',
    'pyopencl',
    'aes256split'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='EasyTranscriber',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='pictures\\icn.ico'
)
